### PR TITLE
Fix stripping out value of blank keys

### PR DESCRIPTION
**Pull request by NullSoldier**
I'm not saying this is the right fix or not, since it "feels a little uglier" but it's definitely technically correct as far as I know. When you have a key with a blank value "",  the parenthesis are removed and the entire line is stripped. It then appears to be the beginning of a section causing the entire file to be parsed incorrectly.

What do you think?

### CODE REVIEW

**Comment by NullSoldier** [comment]
Travis is failing but not because of tests. Hmm

**Comment by leovp** [comment]
Your branch _does_ make Travis fail, and it's because of tests.


But you're correct, there is a bug: empty values cause all following sections to nest one level deeper; and pretty much everything breaks in that case.

I'll look into it, thanks for the pull-request.

**Comment by NullSoldier** [comment]
Thanks!

**Comment by leovp** [comment]
It is done :)
https://pypi.python.org/pypi/steamfiles/0.1.2

**Pull request merged**
